export const CONTAINER_COLOR_BACKGROUND = "#222222";
export const CARD_COLOR_BACKGROUND = "#282828";
export const CARD_COLOR_TEXT = "#F4F4F4";

export const INDICATOR_COLOR_DEFAULT = "#A9A9A9";
export const INDICATOR_COLOR_RED = "##FF0000";
export const INDICATOR_COLOR_YELLOW = "#FFEB33";
export const INDICATOR_COLOR_BLUE = "##366EFF";
